#!/bin/bash
set -e

if [[ ! -f /etc/kubernetes/pki/ca.key ]];then
	echo kubernetes CA 服务不存在!!
	exit
fi
which openssl
if [[ ! $? -eq 0 ]];then
    echo openssl不存在!!
    exit
fi

#初始化openssl subj参数
Issuer=$(openssl x509 -in /etc/kubernetes/pki/ca.crt -noout -text | grep Issuer:)
. <(echo ${Issuer// /} | awk -F: '{print $2}' | tr ',' '\n')


read -p '用户名：' -e Username

read -p '组名：' -e O

read -p 'apiServer地址：' -e SERVERIP
if [[ $SERVERIP == "" ]];then
	SERVERIP="https://192.168.36.160:6443"
	echo $SERVERIP
fi

echo $SERVERIP

openssl genrsa -out ${Username}.key 
openssl req -new -key ${Username}.key -out ${Username}.csr <<-EOF 
$C
$ST
$L
$O
$OU
$Username
$emailAddress


EOF
openssl x509 -req -days 3650 -CA /etc/kubernetes/pki/ca.crt -CAkey /etc/kubernetes/pki/ca.key -CAcreateserial -in ${Username}.csr -out ${Username}.crt <<EOF 


EOF 

cat > config <<EOF
---
apiVersion: v1
kind: Config
clusters:
- name: $CN
  cluster:
    certificate-authority-data: `cat /etc/kubernetes/pki/ca.crt | base64`
    server: $SERVERIP
users:
- name: $Username
  user:
    client-certificate-data: `cat ${Username}.crt | base64`
    client-key-data: `cat ${Username}.key | base64`
contexts:
- name: ${Username}@${CN}
  context:
    cluster: $CN
    user: $Username
current-context: ${Username}@${CN}
EOF

mkdir ${Username} -p
mv ${Username}.* config  ${Username} 
tar czf ${Username}.tgz ${Username} 
rm ${Username} -rf
echo "证书 ${Username} 生成完成"


